# Site wide configuration

title: "#30DayMapChallenge"
description: "Results of our #30DayMapChallenge in November 2019!"
logo: tw30_120x.jpg # 120x120 px default image used for Twitter summary card
teaser: tw30_400x250.jpg #  400x250 px default teaser image used in image archive grid
locale: en
url: https://kevelyn1.github.io/30DayMapChallenge2019
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Evelyn Uuemaa, PhD
  email: 
  twitter: evelynuuemaa
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: evelyn120x.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
